config/routes.rb
Rails.application.routes.draw do

  get   '/users', to: 'users#index'
  post  '/users',  to: 'users#create'
  get   '/users/new', to: 'users#new'
  get   '/users/:id/', to: 'users#show', as: 'user'
  get   '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  put   '/users/:id', to: 'users#update'
  patch '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  resources :posts
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @user.save
    redirect_to @user
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to @user
  end

  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Usercrud</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%#= form_with(model: @user, local: true) do |form| %>

<%= form_for @user do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :email %>
    <%= form.text_field :email%>
  </p>
    <%= form.submit :submit %>
<% end %>

app/views/users/edit.html.erb
<%= render 'form' %>

app/views/users/index.html.erb
<h1> Listing All Data </h1>
<%= link_to 'New Record', users_new_path %>
<table>
  <tr>
    <th> Name </th>
    <th> Email </th>
  </tr>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        
        <td><%= link_to 'Show', user_path(user[:id]) %></td>
        <td><%= link_to 'Edit', edit_user_path(user[:id]) %></td>
        <td><%= link_to 'Destroy', user_path(user), 
                                method: :"delete",
                                data: {confirm: "Are You Sure"} %> </td> 
      </tr>
    <% end %>
</table>

app/views/users/new.html.erb
<%= render 'form' %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Back',users_path %>